### ISSUE TITLE
How can we prevent major version bumps?

### ISSUE THREAD

**Issue by dhalperi** [VirtusLab/bazel-steward#319]
Want to default all upgrades to only be same major version as current.

**Comment by lukaszwawrzyk** [comment]
Hi! There is no direct way to do this for all dependencies automatically.
What you can do, is pin each dependency using update-rules:
```
update-rules:
  - dependencies: commons-io:commons-io
    pin: "2."
  - dependencies: com.typesafe.config
    pin: "3."
```
