### ISSUE TITLE
Log CommandRunner's external process output, notably when it runs post-update-hooks

### ISSUE THREAD

**Issue by vorburger** [VirtusLab/bazel-steward#438]
In the context of https://github.com/VirtusLab/bazel-steward/issues/422, where I attempt to use:

```yaml
post-update-hooks:
  - kinds: bzlmod
    commands:
      - "bazelisk build //..."
    files-to-commit:
      - "MODULE.bazel.lock"
```

Bazel Steward's log looks like it's "stuck" here:

```
[main] INFO org.virtuslab.bazelsteward.app.PullRequestManager - Creating branch bazel-steward/protobuf/29.4, current PR status: OPEN_MODIFIED
[main] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - /usr/bin/git checkout --quiet -b bazel-steward/protobuf/29.4
[main] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - /usr/bin/git add /home/runner/work/enola/enola/MODULE.bazel
[main] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - /usr/bin/git commit --quiet -m "Update protobuf to 29.4"
[main] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - sh -c "bazelisk build //..."
```

it's not actually stuck, because `bazelisk build //...` takes a very long time to run - but it looks like it.

In an ideal world, it might be nice if CommandRunner's would log external process output?

You could use (my!) https://github.com/vorburger/ch.vorburger.exec for this, if you like! 🍀
