### ISSUE TITLE
${group}/${artifact} variables not working in title: for kinds: maven

### ISSUE THREAD

**Issue by vorburger** [VirtusLab/bazel-steward#439]
Since I have added this in https://github.com/enola-dev/enola/commit/f201712d3006420cbfb42eb0dea40f695693fad3 :

```yaml
- title: "Update ${group}/${artifact} from ${versionFrom} to ${versionTo}"
  commit-message: "deps: Update ${group}/${artifact} from ${versionFrom} to ${versionTo}"
  kinds: maven
```

Steward 🤵 raises e.g. https://github.com/enola-dev/enola/pull/1327 where the `${group}/${artifact}` variables work in the commit message, but not PR title.

@lukaszwawrzyk perhaps this is easy to and worth fixing?
