### ISSUE TITLE
Limit number of new/updater PRs per run

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/bazel-steward#51]
Users should be able to configure:
* a maximum number of PRs that Bazel Steward can create or update each time it runs. It can be useful if CI runs are costly and the runs should be distributed in time.
* maximum number of open bazel steward PRs in repo. It can be useful for repositories that have 120 outdated versions and prefer to update them in chunks

Config:

```
pull-requests:
  - limits:
      open: 10
      updates-per-run: 5
```
