### ISSUE TITLE
Configurable Pull Request title template

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/bazel-steward#52]
Similar issue to #44 but for PR titles. It also relates to grouping (#50), as grouped PRs will have custom titles, similarly default 1 change PR can have their title template.

**Comment by lukaszwawrzyk** [comment]
For now we don't need to deal with PR grouping. Let's use config like 

```
pull-requests:
  - title: "[maintenance] Updated {artifact} from {versionFrom} to {versionTo}"
```

Let's at least add "versionFrom", "versionTo", "group", "artifact", "name".
I am wondering how to handle syntax for group/artifact and name, as only maven kind will have group and artifact.

It would be good if users can say:
"Updated {group}/{artifact}"
"Updated {artifact}"
"Updated {name}"

Maybe we should also use generic mechanism of dependency filter in this area? It will play well with grouping later.
```
pull-requests:
  - title "Updated akka-deps"
     dependencies: "org.akka:*"
     group: true
  - title: "Updated {group}/{artifact} to {versionTo}"
     kind: maven
  - title: "Updated {name}"
```

Check how current UpdateRulesConfig and SearchPathConfig are organized and how they use the DependencyFilterApplier (better check UpdateRules part). I think we should just do it the same and ask PullRequestConfigResolver for each UpdateRequest, what title template should be used, then apply it and return as PullRequestSuggestion.
The template applier should pattern match and see if the Library is MavenCoordinates, if so, apply {group} and {artifact} if requested, if not and they were requested, it should be an error. For all other libraries, it should just substitute the common parameters.
